### ISSUE TITLE
Wallet View

### ISSUE THREAD

**Issue by wordyallen** [wordyallen/earlyinterest-ui-sandbox#3]

**Comment by wordyallen** [comment]
# Final Spec
![Wallet_notes_2.12.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56ba3df35011000e00edbbb2/125516c66e82c728ace21e0d46df95962f87979681e6ab46b762a2da7814653f6b14b1247a80e03cfd18395456564fae17580c47adff892daeb63c72dc5c0dead73c0d66da2f53fde6d640e258f075c95d8fa4bf8b46c1ed3d27e1838746371c041c8eed10.png)

# Reference
![Wallet-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56ba3df35011000e00edbbb2/125516c66e82c728ace21e0d46df95962f8797e4deabf301b44fff9e2c4533317346f67229d4b12eef412800595f48a441585d12fcff8e2df7e42e6c981e5ab38532022d8c6853beb2901db80bbb258b4d83beb58a4bc1ed3823f5c6.png)
![Wallet-2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56ba3df35011000e00edbbb2/125516c66e82c728ace21e0d46df95962f8797e4ddabf301b44fff9e2c4533317346f67229d4b12eef412800595f48a441585d12fcff8e2df7e42e6c981e5ab38532022d8c6853beb2901db90bbb258b4d83beb58a4bc1ed3b27f5c6.png)
![Wallet-3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56ba3df35011000e00edbbb2/125516c66e82c728ace21e0d46df95962f8797e4dcabf301b44fff9e2c4533317346f67229d4b12eef412800595f48a441585d12fcff8e2df7e42e6c981e5ab38532022d8c6853beb2901cbe0bbb258b4d83beb58a4bc1ed3b23f5c6.png)
![Wallet.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56ba3df35011000e00edbbb2/125516c66e82c728ace21e0d46df95962f8797ebc3abaf51ab57f5973d047d317c5dfa7a2283b32bec432d5159574eac430e5f42fbffd879b4aa2e32db025fb28c341521842f1bbeba8415be04ba228d478cb6bb8b49c6e92f68.png)

# Deliverables
CSS and JSX for the following view broken down into their respective component files:
## -  `<WalletHeader />`

**Comment by puresparkdesign** [comment]
https://medium.com/hi-my-name-is-jon/fuck-you-pay-me-5ba7b568afe7
